services:
  wiki_app:
    build:
      context: ./wiki_app
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./data:/app/data
    ports:
      - ${WIKI_SERVER_PORT}:8000

  image_app:
    build:
      context: ./image_app
      dockerfile: Dockerfile
    command: gunicorn -w 1 -b 0.0.0.0:8000 app:app
    env_file:
      - .env
    volumes:
      - ./static/images:/app/static/images
      - ${HF_CACHE}:/root/.cache/huggingface
    environment:
      - HF_HOME=/root/.cache/huggingface
    ports:
      - ${IMAGE_SERVER_PORT}:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  data: