services:
  wiki_app:
    build:
      context: ./wiki_app
      dockerfile: Dockerfile
    command: gunicorn --certfile=cert.pem --keyfile=private.key -w 1 -b 0.0.0.0:8000 app:app
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./data:/app/data
      - ./cert.pem:/app/cert.pem
      - ./private.key:/app/private.key
    ports:
      - ${SERVER_PORT}:8000
    networks:
      - shared-network

  image_app:
    build:
      context: ./image_app
      dockerfile: Dockerfile
    command: gunicorn -w 1 -b 0.0.0.0:8000 app:app
    env_file:
      - .env
    volumes:
      - ./static/images:/app/static/images
      - ${HF_CACHE}:/root/.cache/huggingface
    environment:
      - HF_HOME=/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    networks:
      - shared-network

volumes:
  data:

networks:
  shared-network:
    driver: bridge