services:
  wiki_app:
    build:
      context: ./wiki_app
      dockerfile: ../Dockerfile
    volumes:
      - ./static:/app/static
      - ./data:/app/data
    ports:
      - "5001:80"

  image_app:
    build:
      context: ./image_app
      dockerfile: ../Dockerfile
    volumes:
      - ./static/assets:/app/static/assets
    ports:
      - "5002:80"

volumes:
  data:
